<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EC2AMAZ-S11DBRH" failures="2" tests="8" name="Test" time="0.151" errors="0" timestamp="2024-03-23T12:54:35 GMT">
  <testcase classname="TestNgTesting.RerunFailedTestcase" name="test1" time="0.021">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="TestNgTesting.RerunFailedTestcase" name="test1" time="0.004">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="TestNgTesting.RerunFailedTestcase" name="test1" time="0.003">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="TestNgTesting.RerunFailedTestcase" name="test1" time="0.003">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNgTesting.RerunFailedTestcase.test1(RerunFailedTestcase.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase classname="TestNgTesting.RerunFailedTestcase" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="TestNgTesting.RerunFailedTestcase" name="test2" time="0.007">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="TestNgTesting.RerunFailedTestcase" name="test2" time="0.004">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="TestNgTesting.RerunFailedTestcase" name="test2" time="0.005">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNgTesting.RerunFailedTestcase.test2(RerunFailedTestcase.java:10)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
